version: 'Build {build}'
image: Visual Studio 2019
skip_branch_with_pr: true

install:
  - choco install opencover.portable codecov
  - ps: .\build\dotnet-install.ps1 -Version 3.1.300

  
build_script:
  - ps: .\build.appveyor.ps1
  
test: false
artifacts:
  - path: '.\build-artifacts\*'

deploy:
  - provider: NuGet
    artifact: /.*nupkg/
    api_key:
      secure: QNfyCsBxCLb4iGmaRd2ep7yYY3RMJKw54B7p+ZcFDo5pb8KnWM0ULl4ml2u38s/w
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    artifact: /.*nupkg/
    draft: true
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'TODO'
    auth_token:
      secure: 8WGv8noklaCJAQEBpcs+VShk/Hql5zbyx0VPhMvzUw0RcG7rAd2KxKIh4gazXlBi
    on:
      APPVEYOR_REPO_TAG: true
